### ISSUE TITLE
3.3.1 causes the disappearance of some icons on some other tweaks.

### ISSUE THREAD

**Issue by sahinkaa** [jjolano/shadow#62]
I don't know how it is possible, but it causes the disappearance of Rocket for Instagram's some icons and FBFreeze's icons. What is this tweak actually doing? I'm rolling back to 3.3

**Comment by jjolano** [comment]
Nothing has changed, functionally. Have you tried the Tweak Compatibility option?

**Comment by sahinkaa** [comment]
> Nothing has changed, functionally. Have you tried the Tweak Compatibility option?

Yes, now I tried again with that option on, but no luck. 3.3.1: in-app icons from other tweaks are broken, 3.3: working.

Also I don't want to open another case for it now but, I uninstalled it completely for the last 1 day and my keyboard's responsiveness improved dramatically. Also apps are launching faster. iP8+ iOS 12.4 u0. I'm not sure if I need this tweak at all. My banking apps are okay with my jailbreak. Do you think I should keep using it? I would like to help testing the new versions if you are up to fixing these keyboard and app launch time issues. Cheers

**Comment by jjolano** [comment]
To be honest, yours is the only report of sluggish keyboard performance. Only thing i can think of in that case is if you are running a (poorly designed) keyboard tweak causing Shadow to constantly verify filesystem accesses. I run Laetus to theme my keyboard and have no issues. I apologize for the issue you are experiencing.

Nothing from 3.3 to 3.3.1 has changed other than rewriting initialization code to reduce chances of crashing, so im quite stumped as to how it can make such an effect.

In your case, I recommend not using the "Always-On" option as it sounds like that is turned on. And just configure it per application as needed. Shadow will do nothing otherwise.

You can also disable Shadow Service if you have that enabled, and that way there is no additional latency from querying outside the sandbox.

Personally, I use always on with my setup along with every single bypass option turned on and experience no issues whatsoever. I am currently looking into improving performance where possible. However one fundamental difference is that we run different code injection platforms: yours Substitute and mine libhooker. Its difficult to debug an issue that i dont experience, and until i get my hands on a Substitute device it will remain that way.

**Comment by sahinkaa** [comment]
Thank you for your detailed explanations. You're on the right path. If I ever need jb bypass for some reason, I will install it and set settings per app basis. If Iand come by something to report then, I will do so. Kind regards. Keep on..

**Comment by jjolano** [comment]
I will close this issue for now. It does seem like a tweak compatibility issue but im currently unable to replicate anything like it.

**Comment by sahinkaa** [comment]
I can confirm that it is fixed with 3.3.5
